version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: daily
          time: '21:00'
      open-pull-requests-limit: 10
      groups:
          typescript-eslint:
              patterns:
                  - "@typescript-eslint*"
          sentry:
              patterns:
                  - "@sentry*"
